version: '3'
services:
  opengym:
    build:
      context: .
    tty: true
    volumes:
    - ./notebooks:/root/src/notebooks
    ports: 
      - "8888:8888"
    command: jupyter-lab --ip 0.0.0.0 --allow-root -b localhost --NotebookApp.token=''
